### ISSUE TITLE
咨询random_forest demo的Prediction结果

### ISSUE THREAD

**Issue by ZhangQiusi** [fedlearnAI/fedlearn-algo#30]
冒昧求教：框架中的random_forest demo处理的是一个二分类问题，
1、为什么Prediction的结果是一个有9个元素的数组？我猜测预测的是不是inference数据集中9位uid得糖尿病的概率？如果是这样的话如何去检查预测的准确度呢？
2、为什么每次运行Prediction的结果都是不同的？

**Comment by guabao** [comment]
您好，请提供您使用的数据，执行的代码，预期的结果和最终得到的结果。没有这些内容我们没有办法解答您的问题。

Best regards,
Jiazhou

**Comment by ZhangQiusi** [comment]
感谢您的回复。
我指的是框架安装好后，fedlearn-algo/demos/random_forest/demo_local.py直接测试运行的结果，demo中示例的数据集是diadetes，最终输出的prediction是一个9元素的数组。

**Comment by guabao** [comment]
我不太确定您说的diadetes指的是什么，如果是直接运行demo_local.py的话使用的是 data/classificationA 的示例数据，其中在inference部分有9个sample，对应有9个prediction score，也就是您看到的9元素数组。至于预测结果不同，应该主要是由于随机森林的特征/样本是随机选取的，通过fix random seed应该可以得到固定的结果。

Best regards,
Jiazhou

**Comment by ZhangQiusi** [comment]
抱歉，我敲错了单词，diabetes，指的正是框架data/classificationA的示例数据，看数据是PimaIndiansdiabetes数据集拆分而来。
再次感谢您的回复。
