### ISSUE TITLE
Need fix for core.encrypt.RandomizedIterativeAffine module for combinatory operations

### ISSUE THREAD

**Issue by flyingcat047** [fedlearnAI/fedlearn-algo#6]
I found one problem of `core.encrypt.RandomizedIterativeAffine` module.
When combinatory scalar products and additions are applied to the encrypted objects, the result may turn wrong.
For example, with the inputs below,
```
p1= 4592.146866155027
p2= 532.2228109095383
k1= 872.0311515320057
k2= -1033.819189454349
```
the decrypted result of `([p1]*k1)*k2+[p2]` is `-532.2228107452393`
I also tried with other inputs. It seems that the decryption of `([p1]*k1)*k2+[p2]` generally gives me the value of -`p2`

**Comment by cyqclark** [comment]
Thanks for reporting the issue!
We updated code base via pull request #9 and it should solve this problem.

Closing this issue.
